import React, {useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Film,Plus,FolderOpen,Upload,Scissors,LayoutTemplate,Mic2,Music2,Sparkles,Play,Download,Undo2,Save,ChevronLeft,ChevronRight,Trash2,X,Check,Loader2,Image as ImageIcon,SlidersHorizontal,Clapperboard,Volume2,PanelLeftClose,ArrowRight,Copy,FileText,CheckCircle2,AlertCircle,RefreshCw,Send,Layers,KeyRound,Eye,EyeOff,ClipboardPaste} from 'lucide-react';
import './style.css';
import '@fontsource/be-vietnam-pro/vietnamese-400.css';
import '@fontsource/be-vietnam-pro/vietnamese-500.css';
import '@fontsource/be-vietnam-pro/vietnamese-600.css';
import '@fontsource/be-vietnam-pro/vietnamese-700.css';
import '@fontsource/be-vietnam-pro/latin-400.css';
import '@fontsource/be-vietnam-pro/latin-500.css';
import '@fontsource/be-vietnam-pro/latin-600.css';
import '@fontsource/be-vietnam-pro/latin-700.css';

async function api(path,body,method){
  const opts={method:method||(body===undefined?'GET':'POST')};
  if(body!==undefined){opts.body=body instanceof FormData?body:JSON.stringify(body);if(!(body instanceof FormData))opts.headers={'Content-Type':'application/json'};}
  const response=await fetch('/api'+path,opts);const data=await response.json();
  if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail||data));return data;
}
const clone=x=>structuredClone(x);
const fmt=n=>`${Math.floor(n/60).toString().padStart(2,'0')}:${(n%60).toFixed(1).padStart(4,'0')}`;
const aid=(p,id)=>p.assets.find(a=>a.id===id);
const mediaUrl=(p,id)=>`/api/projects/${p.id}/assets/${id}/file`;
const thumbUrl=(p,name)=>name?`/api/projects/${p.id}/thumbs/${name}`:'';
const exportUrl=(p,e,name)=>`/api/projects/${p.id}/exports/${e.id}/${name||e.filename}`;
const tabs=[['media','Tư liệu',FolderOpen],['script','Kịch bản',FileText],['template','Mẫu dựng',LayoutTemplate],['audio','Âm thanh',Mic2],['ai','Trợ lý AI',Sparkles]];
const roleNames={source:'Nguồn dựng',reference:'Video mẫu',voice:'Giọng đọc',music:'Nhạc nền',overlay:'Logo / biểu tượng'};

function Button({children,icon:Icon,primary=false,small=false,...props}){return <button className={`${primary?'primary':''} ${small?'small':''}`} {...props}>{Icon&&<Icon size={small?14:16}/>} {children}</button>}
function Field({label,children,hint}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
function NumberField({label,value,onChange,min=0,max=100,step=.1}){return <Field label={label}><input type="number" value={value} min={min} max={max} step={step} onChange={e=>onChange(Number(e.target.value))}/></Field>}
function Empty({icon:Icon=Film,title,children}){return <div className="empty"><Icon size={34}/><h3>{title}</h3><p>{children}</p></div>}

function App(){
 const [projects,setProjects]=useState([]),[p,setP]=useState(null),[tab,setTab]=useState('media'),[selected,setSelected]=useState(0),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[jobs,setJobs]=useState([]),[toast,setToast]=useState(''),[error,setError]=useState(''),[settings,setSettings]=useState(null),[templates,setTemplates]=useState([]),[useAI,setUseAI]=useState(false),[proposal,setProposal]=useState(null),[preview,setPreview]=useState(null),[preflight,setPreflight]=useState(null),[schemaBackups,setSchemaBackups]=useState([]),[showSettings,setShowSettings]=useState(false),[showProjects,setShowProjects]=useState(true),[play,setPlay]=useState(false),[cursor,setCursor]=useState(0);
 const pRef=useRef(p),dirtyRef=useRef(dirty),jobSeen=useRef(new Set());
 useEffect(()=>{pRef.current=p;dirtyRef.current=dirty},[p,dirty]);
 const loadProjects=()=>api('/projects').then(list=>{setProjects(list);return list;});
 useEffect(()=>{loadProjects().then(list=>{const id=localStorage.getItem('clipforge-project');if(list.some(x=>x.id===id&&!x.corrupt))safe(()=>open(id));});Promise.all([api('/templates'),api('/template-packages')]).then(([all,packages])=>setTemplates([...all.filter(x=>['clean','editorial','bold'].includes(x.id)).map(template=>({id:template.id,name:template.name,template,built_in:true,missing_assets:[]})),...packages]));api('/settings').then(setSettings)},[]);
 useEffect(()=>{if(!p?.id)return;let cancelled=false;api(`/projects/${p.id}/schema-backups`).then(info=>{if(!cancelled)setSchemaBackups(info.backups||[])}).catch(()=>{});return()=>{cancelled=true}},[p?.id,p?.revision]);
 useEffect(()=>{const guard=e=>{if(dirtyRef.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[]);
 useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(timer)}},[toast]);
 const safe=async fn=>{setError('');setBusy(true);try{return await fn()}catch(e){setError(e.message);return null}finally{setBusy(false)}};
 const open=async id=>{if(dirtyRef.current)await save();const project=await api('/projects/'+id);const history=await api('/jobs?pid='+id);history.filter(j=>['done','error','cancelled'].includes(j.status)).forEach(j=>jobSeen.current.add(j.id));localStorage.setItem('clipforge-project',id);setJobs(history);setP(project);setDirty(false);setSelected(0);setCursor(0);setPreview(null);setPreflight(null);setProposal(null);setPlay(false);};
 const edit=fn=>{if(busy||jobs.some(j=>['running','queued'].includes(j.status)))return;setP(old=>{const next=clone(old);fn(next);return next});setDirty(true);setPreview(null);setPreflight(null);setPlay(false)};
 const save=async()=>{if(!pRef.current)return null;const next=await api('/projects/'+pRef.current.id,pRef.current,'PUT');setP(next);pRef.current=next;setDirty(false);dirtyRef.current=false;await loadProjects();return next;};
 const create=()=>safe(async()=>{if(dirty)await save();const next=await api('/projects',{name:'Video mới',mode:'remix'});setP(next);setDirty(false);setSelected(0);setCursor(0);setPreview(null);setPreflight(null);setProposal(null);await loadProjects()});
 const recover=item=>safe(async()=>{const restored=await api(`/projects/${item.id}/recover`,{});await loadProjects();setToast('Đã phục hồi dự án từ lịch sử hợp lệ');if(p?.id===item.id){setP(restored);pRef.current=restored;setDirty(false);setPreview(null)}});
 const useEnvironmentSecret=(secret,draft)=>safe(async()=>{await api('/settings',draft,'PUT');const next=await api('/settings/use-environment',{secret});setSettings(next);setToast('Đã chuyển cấu hình sang dùng biến môi trường');return next});
 const active=jobs.find(j=>['running','queued'].includes(j.status));
 useEffect(()=>{if(!p?.id)return;let cancelled=false;const tick=async()=>{try{const list=await api('/jobs?pid='+p.id);if(cancelled)return;setJobs(list);for(const j of list){if(['done','error','cancelled'].includes(j.status)&&!jobSeen.current.has(j.id)){jobSeen.current.add(j.id);if(j.status==='error')setError(j.message);if(j.status==='done'){if(j.kind==='assistant')setProposal(j.result);else if(!dirtyRef.current){const updated=await api('/projects/'+p.id);if(cancelled)return;setP(updated);pRef.current=updated;if(j.kind==='render'){setPreview(updated.exports.at(-1));setPlay(false)}await loadProjects();}setToast('Đã hoàn tất '+({analyze:'phân tích cảnh',plan:'lập timeline',voice:'tạo giọng',template:'phân tích mẫu',render:'xuất video',transcribe:'căn phụ đề',demo:'dự án mẫu',assistant:'đề xuất AI'}[j.kind]||''));}}}}catch(e){if(!cancelled)setError(e.message)}};tick();const t=setInterval(tick,1200);return()=>{cancelled=true;clearInterval(t)}},[p?.id]);
 const run=(name,body={})=>safe(async()=>{setPlay(false);if(dirtyRef.current)await save();if(name==='render'){const report=await api(`/projects/${pRef.current.id}/preflight`);setPreflight(report);if(!report.ok){setToast('Sửa các lỗi kiểm tra trước khi xuất video.');return null;}}const job=await api(`/projects/${pRef.current.id}/${name}`,body);setJobs(old=>[...old,job]);return job;});
 const applyTemplate=(id,assetMap={})=>safe(async()=>{if(dirtyRef.current)await save();const next=await api(`/projects/${pRef.current.id}/templates/${id}/apply`,{asset_map:assetMap});setP(next);pRef.current=next;setDirty(false);setPreview(null);setPreflight(null);setToast('Đã áp dụng template và nhập tài nguyên vào dự án');});
 const regenerateCues=()=>safe(async()=>{if(dirtyRef.current)await save();const current=pRef.current;const next=await api(`/projects/${current.id}/cues/regenerate`,{revision:current.revision});setP(next);pRef.current=next;setDirty(false);setPreflight(null);setToast('Đã tạo lại mốc phụ đề');});
 const confirmCues=()=>safe(async()=>{if(dirtyRef.current)await save();const current=pRef.current;const next=await api(`/projects/${current.id}/cues/confirm`,{revision:current.revision});setP(next);pRef.current=next;setDirty(false);setPreflight(null);setToast('Đã xác nhận giữ các mốc phụ đề hiện tại');});
 const upload=(files,role)=>{const chosen=Array.from(files);return safe(async()=>{if(!chosen.length)return;if(dirtyRef.current)await save();const form=new FormData();chosen.forEach(f=>form.append('files',f));form.append('role',role);const next=await api(`/projects/${p.id}/assets`,form);setP(next);pRef.current=next;setDirty(false);setToast('Đã nhập '+chosen.length+' tư liệu');});};
 const demo=()=>safe(async()=>{if(dirtyRef.current)await save();const data=await api('/demo',{});setP(data.project);setDirty(false);setSelected(0);setCursor(0);setPreview(null);setJobs([data.job]);await loadProjects()});
 const duration=p?.clips.reduce((n,c)=>n+c.duration,0)||0;
 useEffect(()=>{if(p){if(selected>=p.clips.length)setSelected(Math.max(0,p.clips.length-1));if(cursor>duration)setCursor(duration)}},[p?.clips.length,duration]);
 const locked=busy||!!active;
 const selectClip=i=>{setSelected(i);setCursor(p.clips.slice(0,i).reduce((n,c)=>n+c.duration,0));setPlay(false);setPreview(null)};
 const addScene=(a,sc)=>edit(n=>{n.clips.push({id:crypto.randomUUID().replaceAll('-','').slice(0,16),asset_id:a.id,scene_id:sc?.id||'',source_start:sc?.start||0,duration:Math.min(3,sc?sc.end-sc.start:(a.duration||3)),speed:1,fit:'cover',crop_x:.5,crop_y:.5,title:n.name,caption:'',transition:'cut',layers:[]})});
 return <div className="app-shell">
  <header className="topbar"><div className="brand"><div className="brand-icon"><Clapperboard size={22}/></div><b>clipforge<span>STUDIO</span></b></div><span className="local-badge"><i/> LOCAL WORKSPACE</span><div className="top-actions"><span className="muted">Video ngắn. Câu chuyện của bạn.</span><span className={'api-status '+(settings?.ai_profiles?.some(x=>x.enabled&&x.api_key)?'ready':'missing')}>{settings?.ai_profiles?.some(x=>x.enabled&&x.api_key)?'AI đã kết nối':'Chưa có API AI'}</span><Button icon={KeyRound} onClick={()=>setShowSettings(true)}>Cài đặt API</Button></div></header>
  <div className={`workspace ${!showProjects?'collapsed':''}`}>
   <aside className="project-sidebar"><div className="sidebar-head"><span>DỰ ÁN CỦA BẠN</span><button className="icon-button" aria-label="Tạo dự án" disabled={locked} onClick={create}><Plus size={18}/></button></div><div className="project-list">{projects.map(item=>item.corrupt?<div key={item.id} className="project-item project-corrupt"><AlertCircle size={18}/><span><strong>{item.name}</strong><small>{item.recovery_available?'Có thể phục hồi từ lịch sử':'Không có lịch sử hợp lệ'}</small></span><Button small disabled={locked||!item.recovery_available} onClick={()=>recover(item)}>Phục hồi</Button></div>:<button disabled={locked} key={item.id} className={`project-item ${p?.id===item.id?'selected':''}`} onClick={()=>safe(()=>open(item.id))}><Film size={18}/><span><strong>{item.name}</strong><small>{item.mode==='template'?'Theo mẫu':'Tái biên tập'} · {item.clips} cảnh</small></span></button>)}</div><div className="sidebar-bottom"><div className="mini-label">BẮT ĐẦU NHANH</div><button className="sample-card" onClick={demo} disabled={locked}><span className="sample-art">✦</span><span>Thử dự án mẫu<small>5 cảnh · nhạc · timeline</small></span><ArrowRight size={16}/></button><small className="storage-note">Tư liệu được lưu trên máy.<br/>AI sử dụng API bạn cấu hình.</small></div></aside>
   <main className="main-workspace">
    {!p?<div className="welcome"><div className="welcome-symbol"><Clapperboard size={58}/></div><span className="eyebrow">KHÔNG GIAN DỰNG VIDEO CỦA BẠN</span><h1>Từ tư liệu thô<br/>đến <em>câu chuyện ngắn.</em></h1><p>Tạo video 30–45 giây theo mẫu hoặc ghép cảnh theo kịch bản.<br/>Giữ mọi bản dựng trong một không gian trên máy của bạn.</p><div className="welcome-actions"><Button primary icon={Plus} onClick={create} disabled={locked}>Tạo video đầu tiên</Button><Button icon={Play} onClick={demo} disabled={locked}>Khám phá dự án mẫu</Button></div><div className="welcome-modes"><div><LayoutTemplate/><b>Dựng theo mẫu</b><span>Khung, biểu tượng và nhịp dựng nhất quán.</span></div><div><Scissors/><b>Tái biên tập</b><span>Chọn cảnh từ 5–10 video theo lời đọc.</span></div><div><Sparkles/><b>AI bên cạnh</b><span>Tìm cảnh, tạo voice và đề xuất chỉnh sửa.</span></div></div></div>:<>
    <div className="project-toolbar"><button className="icon-button" title="Ẩn/hiện danh sách" onClick={()=>setShowProjects(!showProjects)}><PanelLeftClose size={18}/></button><input className="project-name" aria-label="Tên dự án" value={p.name} disabled={locked} onChange={e=>edit(n=>n.name=e.target.value)}/><span className="save-state">{dirty?'Chưa lưu':'Đã lưu trên máy'}</span><div className="toolbar-actions">{schemaBackups.length>0&&<details className="schema-backup-menu"><summary className="button small schema-backup-link" title="Tải bản JSON gốc và media đã sao lưu; hướng dẫn khôi phục nằm trong manifest của ZIP"><Download size={14}/>Bản gốc ({schemaBackups.length})</summary><div className="schema-backup-options">{schemaBackups.slice().reverse().map(backup=><a key={backup.id} href={`/api/projects/${p.id}/schema-backups/${backup.id}/download`} download title={`${backup.asset_count} file media đã sao lưu${backup.missing_assets.length?` · thiếu ${backup.missing_assets.length}`:''}`}>Schema {backup.source_schema_version} · {new Date(backup.created_at).toLocaleString()}</a>)}</div></details>}<Button small icon={Undo2} disabled={locked} onClick={()=>safe(async()=>{if(dirtyRef.current)await save();const next=await api(`/projects/${p.id}/undo`,{});setP(next);setDirty(false);setPreview(null)})}>Hoàn tác</Button><Button small icon={Save} disabled={locked||!dirty} onClick={()=>safe(save)}>Lưu</Button><Button small primary icon={Download} disabled={locked||!p.clips.length} onClick={()=>run('render',{preview:false})}>Xuất video</Button></div></div>
    <div className="editor-grid">
     <section className="control-pane"><nav className="tabs">{tabs.map(([key,label,Icon])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon size={19}/><span>{label}</span></button>)}</nav><div className="control-scroll">
      <div className="mode-selector"><button disabled={locked} className={p.mode==='remix'?'active':''} onClick={()=>edit(n=>n.mode='remix')}><Scissors size={15}/>Tái biên tập</button><button disabled={locked} className={p.mode==='template'?'active':''} onClick={()=>edit(n=>n.mode='template')}><LayoutTemplate size={15}/>Theo mẫu</button></div>
      {tab==='media'&&<MediaPanel {...{p,upload,locked,run,useAI,setUseAI,edit,addScene}} onDelete={id=>safe(async()=>{if(dirtyRef.current)await save();const next=await api(`/projects/${p.id}/assets/${id}`,undefined,'DELETE');setP(next);pRef.current=next;setToast('Đã gỡ tư liệu. Có thể dùng Hoàn tác để khôi phục chỉnh sửa.')})}/>}
      {tab==='script'&&<ScriptPanel {...{p,edit,locked,run,useAI,setUseAI}} onRegenerateCues={regenerateCues} onConfirmCues={confirmCues}/>}
      {tab==='template'&&<TemplatePanel {...{p,edit,locked,templates,run,useAI,setUseAI,applyTemplate}} onSave={()=>safe(async()=>{const t=await api(`/projects/${p.id}/templates`,p.template);setTemplates(old=>[...old,t]);setToast('Đã đóng gói mẫu cùng tài nguyên ảnh')})}/>}
      {tab==='audio'&&<AudioPanel {...{p,edit,locked,run,upload}} settings={settings} onSettings={()=>setShowSettings(true)}/>}
      {tab==='ai'&&<AssistantPanel {...{p,locked,run,proposal}} onApply={()=>safe(async()=>{if(dirtyRef.current)await save();const next=await api(`/projects/${p.id}/apply-ai`,proposal);setP(next);setDirty(false);setProposal(null);setPreview(null)})} onSettings={()=>setShowSettings(true)}/>}
     </div></section>
     <section className="preview-pane"><div className="section-heading"><span><i className="dot"/> XEM TRƯỚC</span><div className="select-inline"><select aria-label="Tỷ lệ khung" disabled={locked} value={p.aspect} onChange={e=>edit(n=>n.aspect=e.target.value)}><option>9:16</option><option>16:9</option><option>1:1</option></select><select aria-label="Độ phân giải" disabled={locked} value={p.resolution} onChange={e=>edit(n=>n.resolution=e.target.value)}><option value="1080">1080p</option><option value="720">720p</option></select></div></div>
       <Preview {...{p,selected,preview,play,setPlay,cursor,setCursor,duration}} onSelect={setSelected}/>
       <div className="preview-controls"><Button small icon={Play} disabled={!p.clips.length} onClick={()=>{setPreview(null);if(cursor>=duration)setCursor(0);setPlay(!play)}}>{play?'Tạm dừng':'Phát timeline'}</Button><span className="timecode">{fmt(cursor)} <span>/ {fmt(duration)}</span></span><Button small icon={RefreshCw} disabled={locked||!p.clips.length} onClick={()=>run('render',{preview:true})}>Dựng xem thử</Button></div>
       {!preview&&<input aria-label="Vị trí phát" className="scrubber" type="range" min="0" max={duration||1} step=".05" value={Math.min(cursor,duration)} disabled={!p.clips.length} onChange={e=>{setCursor(Number(e.target.value));setPlay(false)}}/>}<small className="preview-note">{preview?'Bản MP4 đã dựng · '+preview.width+' × '+preview.height:'Xem nhanh bố cục. Dựng xem thử để kiểm tra chính xác hiệu ứng và âm thanh.'}</small>
     </section>
     <aside className="inspector"><div className="section-heading"><span><SlidersHorizontal size={15}/> CHỈNH CẢNH</span><span className="count-pill">{p.clips.length?String(selected+1).padStart(2,'0'):'—'}</span></div><ClipInspector {...{p,selected,edit,locked}}/><div className="export-history"><h4>Bản xuất gần đây</h4>{p.exports.length===0?<p className="muted">MP4 và phụ đề sẽ xuất hiện ở đây.</p>:p.exports.slice(-4).reverse().map(e=><div className="export-item" key={e.id}><button onClick={()=>{setPreview(e);setPlay(false)}}><Play size={14}/>{e.preview?'Xem thử':'Video'} · {e.duration}s</button><a href={exportUrl(p,e)} download={`${p.name}.mp4`} title="Tải MP4"><Download size={15}/></a><a href={exportUrl(p,e,'captions.srt')} title="Tải SRT">SRT</a></div>)}<a className="text-link" href={`/api/projects/${p.id}/download`} download>Xuất dự án JSON</a></div></aside>
    </div>
    <section className="timeline"><div className="timeline-heading"><div><Layers size={17}/><b>Timeline</b><span>{p.clips.length} cảnh</span></div><div><label className="ai-toggle"><input type="checkbox" checked={useAI} onChange={e=>setUseAI(e.target.checked)}/>AI chọn cảnh</label><Button primary small icon={Sparkles} disabled={locked} onClick={()=>run('plan',{use_ai:useAI})}>Tự động dựng</Button></div></div>
      <div className="timeline-scroll"><div className="ruler">{Array.from({length:Math.ceil(Math.max(duration,36)/5)+1},(_,i)=><span key={i}>{fmt(i*5)}</span>)}</div><div className="clip-track">{p.clips.length?p.clips.map((c,i)=>{const a=aid(p,c.asset_id);const sc=a?.scenes.find(s=>s.id===c.scene_id);return <button draggable={!locked} onDragStart={e=>e.dataTransfer.setData('text/plain',String(i))} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(locked)return;const from=Number(e.dataTransfer.getData('text/plain'));if(Number.isInteger(from)&&from>=0&&from<p.clips.length)edit(n=>{const [moved]=n.clips.splice(from,1);n.clips.splice(i,0,moved);setSelected(i)})}} style={{minWidth:Math.max(82,c.duration*35)}} className={`timeline-clip ${i===selected?'selected':''}`} key={c.id} onClick={()=>selectClip(i)}><img src={thumbUrl(p,sc?.thumbnail||a?.thumbnail)} alt=""/><span className="clip-index">{String(i+1).padStart(2,'0')}</span><span className="clip-duration">{c.duration.toFixed(1)}s</span><small>{a?.name}</small></button>}):<div className="timeline-empty">Nhập tư liệu → Phân tích cảnh → Tự động dựng</div>}</div><div className="audio-track"><Mic2 size={13}/><div className={p.voice_id?'voice waveform':'placeholder-track'}>{p.voice_id?aid(p,p.voice_id)?.name:'Thêm giọng đọc hoặc tạo từ kịch bản'}</div></div><div className="audio-track"><Music2 size={13}/><div className={p.music_id?'music waveform':'placeholder-track'}>{p.music_id?aid(p,p.music_id)?.name:'Thêm nhạc nền'}</div></div></div>
    </section>
    {p.warnings.length>0&&<div className="warnings"><AlertCircle size={14}/><span>{p.warnings.join(' ')}</span></div>}
    {preflight?.issues?.length>0&&<section className="preflight-panel" aria-live="polite"><strong>Kiểm tra trước khi xuất · {preflight.ok?'Có lưu ý cần xem':'Cần sửa trước khi xuất'}</strong>{preflight.issues.map((issue,i)=><div className={'preflight-issue '+issue.severity} key={issue.code+'-'+i}><b>{issue.code}</b><span>{issue.message}</span><small>{issue.fix}</small></div>)}</section>}
    </>}
   </main>
  </div>
  {active&&<div className="job-banner"><Loader2 className="spin" size={18}/><div><b>{active.message}</b><div className="progress"><i style={{width:active.progress+'%'}}/></div></div><span>{Math.round(active.progress)}%</span><Button small onClick={()=>safe(()=>api('/jobs/'+active.id+'/cancel',{}))}>Hủy</Button></div>}
  {error&&<div className="error-toast" role="alert"><AlertCircle size={18}/><span>{error}</span><button onClick={()=>setError('')} aria-label="Đóng lỗi"><X size={16}/></button></div>}
  {toast&&<div className="toast"><CheckCircle2 size={17}/>{toast}</div>}
  {showSettings&&settings&&<SettingsModal settings={settings} onClose={()=>setShowSettings(false)} onUseEnvironment={useEnvironmentSecret} onSave={s=>safe(async()=>{const next=await api('/settings',s,'PUT');setSettings(next);setToast('Đã lưu cài đặt API');setShowSettings(false)})} onTest={(s,id)=>safe(async()=>{const next=await api('/settings',s,'PUT');setSettings(next);const result=await api('/settings/test',{profile_id:id,allow_fallback:false});setToast(result.message||'Kết nối AI thành công');return {settings:next,message:result.message||'Kết nối AI thành công',route:result.route}})}/>}
 </div>
}

function MediaPanel({p,upload,locked,run,useAI,setUseAI,edit,addScene,onDelete}){
 const [role,setRole]=useState('source'),[view,setView]=useState('files'),[search,setSearch]=useState('');const input=useRef();
 const files=p.assets.filter(a=>a.role===role&&!a.deleted);const scenes=p.assets.filter(a=>a.role==='source'&&!a.deleted).flatMap(a=>a.scenes.map(sc=>({a,sc}))).filter(({a,sc})=>(sc.tags+' '+a.name).toLowerCase().includes(search.toLowerCase()));
 return <><div className="panel-title"><h2>Thư viện tư liệu</h2><span>{p.assets.filter(a=>!a.deleted).length} file</span></div><Field label="Nhập tư liệu vào"><select value={role} onChange={e=>setRole(e.target.value)}>{Object.entries(roleNames).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></Field><button className="dropzone" disabled={locked} onClick={()=>input.current.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!locked)upload(e.dataTransfer.files,role)}}><Upload size={25}/><strong>Kéo thả hoặc chọn file</strong><span>Tối đa 10 file mỗi lần · MP4, MOV, ảnh, audio</span></button><input ref={input} hidden type="file" multiple onChange={e=>{upload(e.target.files,role);e.target.value=''}} accept="video/*,audio/*,image/*"/>
 <div className="row spread"><div className="segmented"><button className={view==='files'?'active':''} onClick={()=>setView('files')}>Tư liệu</button><button className={view==='scenes'?'active':''} onClick={()=>setView('scenes')}>Cảnh ({scenes.length})</button></div><Button small icon={Scissors} disabled={locked} onClick={()=>run('analyze',{use_ai:useAI})}>Phân tích</Button></div><label className="ai-toggle"><input type="checkbox" checked={useAI} onChange={e=>setUseAI(e.target.checked)}/>Dùng AI để hiểu nội dung từng cảnh</label>
 {view==='files'?<div className="asset-list">{!files.length&&<Empty icon={FolderOpen} title="Chưa có tư liệu">Thêm {roleNames[role].toLowerCase()} để bắt đầu.</Empty>}{files.map(a=><article className="asset-card" key={a.id}><div className="asset-thumb">{a.thumbnail?<img src={thumbUrl(p,a.thumbnail)} alt={a.name}/>:<Music2 size={25}/>}<span>{a.duration?a.duration.toFixed(1)+'s':'ẢNH'}</span></div><div className="asset-info"><strong title={a.name}>{a.name}</strong><small>{a.width?`${a.width} × ${a.height} · `:''}{a.scenes.length} cảnh</small><input placeholder="Nhãn: biển, núi, sản phẩm…" aria-label={'Nhãn '+a.name} value={a.tags} disabled={locked} onChange={e=>edit(n=>{n.assets.find(x=>x.id===a.id).tags=e.target.value})}/></div><div className="asset-buttons">{a.role==='source'&&a.media!=='audio'&&<button className="icon-button" disabled={locked} title="Thêm vào timeline" onClick={()=>addScene(a,a.scenes[0])}><Plus size={15}/></button>}<button className="icon-button" disabled={locked} title="Gỡ tư liệu" onClick={()=>onDelete(a.id)}><X size={14}/></button></div></article>)}</div>:<><input className="search" placeholder="Tìm theo nội dung cảnh…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="scene-grid">{scenes.map(({a,sc})=><button key={sc.id} className="scene-card" disabled={locked} onClick={()=>addScene(a,sc)} title={sc.tags}><img src={thumbUrl(p,sc.thumbnail)} alt={sc.tags}/><span>{fmt(sc.start)} · {(sc.end-sc.start).toFixed(1)}s</span><small>{sc.tags}</small><Plus size={14}/></button>)}</div></>}
 <p className="helper">Phân tích một lần; các lần dựng sau dùng lại thư viện cảnh. Video nguồn được tắt tiếng khi ghép với voice và nhạc.</p></>
}

function ScriptPanel({p,edit,locked,run,useAI,setUseAI,onRegenerateCues,onConfirmCues}){
 const regenerate=()=>{
  if((p.cues_edited||p.cues_stale)&&p.cues.length&&!window.confirm('Tạo lại sẽ thay toàn bộ nội dung và thời gian của các cue hiện tại. Tiếp tục?'))return;
  onRegenerateCues();
 };
 return <><div className="panel-title"><h2>Câu chuyện của bạn</h2><FileText size={20}/></div><p className="helper">Mỗi câu mô tả một ý. Timeline sẽ chọn hình phù hợp với từng đoạn lời đọc.</p><textarea className="script-input" value={p.script} disabled={locked} placeholder="Dán kịch bản 30–45 giây tại đây…" onChange={e=>edit(n=>{n.script=e.target.value;if(n.cues.length)n.cues_stale=true})}/><div className="row spread"><small className="muted">{p.script.trim().split(/\s+/).filter(Boolean).length} từ · {p.script.length} ký tự</small><span className="count-pill">{p.cues_stale?'Kịch bản đổi · cần xem lại':p.cues_edited?'Đã chỉnh thủ công':p.cue_timing==='estimated'?'Mốc ước lượng':'Đã có mốc voice'}</span></div><NumberField label="Thời lượng mong muốn (giây)" value={p.target_duration} min={5} max={180} step={1} onChange={v=>edit(n=>n.target_duration=v)}/><p className="helper">Mặc định 36 giây. Nếu voice dài hơn, công cụ giữ trọn lời đọc và kéo dài timeline.</p><div className="button-stack"><Button icon={Mic2} disabled={locked||!p.script.trim()} onClick={()=>run('voice')}>Tạo giọng từ kịch bản</Button><Button primary icon={Sparkles} disabled={locked} onClick={()=>run('plan',{use_ai:useAI})}>Ghép cảnh theo kịch bản</Button></div>{p.cues_stale&&<div className="cue-stale"><span>Kịch bản đã đổi. Có thể sửa cue hoặc xác nhận giữ nguyên các mốc hiện tại.</span><div className="row"><Button small disabled={locked||!p.script.trim()} onClick={onConfirmCues}>Đã kiểm tra, giữ cue</Button><Button small disabled={locked||!p.script.trim()} onClick={regenerate}>Tạo lại cue</Button></div></div>}<details className="advanced"><summary>Chỉnh mốc phụ đề ({p.cues.length})</summary><div className="cue-actions"><small>Mốc gốc: {p.cue_timing==='estimated'?'ước lượng theo kịch bản':p.cue_timing}. Chỉnh cue sẽ đánh dấu đã xem; thao tác tạo lại thay toàn bộ cue hiện tại.</small><Button small icon={RefreshCw} disabled={locked||!p.script.trim()} onClick={regenerate}>Tạo lại mốc</Button></div><div className="cue-list">{p.cues.map((c,i)=><div className="cue-row" key={i}><input aria-label="Bắt đầu phụ đề" type="number" step=".1" value={c.start.toFixed(2)} onChange={e=>edit(n=>{n.cues[i].start=Number(e.target.value);n.cues_edited=true;n.cues_stale=false})}/><input aria-label="Kết thúc phụ đề" type="number" step=".1" value={c.end.toFixed(2)} onChange={e=>edit(n=>{n.cues[i].end=Number(e.target.value);n.cues_edited=true;n.cues_stale=false})}/><input aria-label="Nội dung phụ đề" value={c.text} onChange={e=>edit(n=>{n.cues[i].text=e.target.value;n.cues_edited=true;n.cues_stale=false})}/></div>)}</div></details></>}

function TemplatePanel({p,edit,locked,templates,run,useAI,setUseAI,onSave,applyTemplate}){
 const [ref,setRef]=useState(''),[json,setJson]=useState(''),[jsonError,setJsonError]=useState(''),[replacements,setReplacements]=useState({});const t=p.template;
 const addLayer=kind=>edit(n=>n.template.layers.push({id:crypto.randomUUID().slice(0,8),kind,x:.1,y:.1,w:kind==='circle'?.15:.8,h:.12,text:kind==='text'?'{title}':'',size:52,color:'#ffffff',background:'#101010',opacity:1,asset_id:'',animation:'none'}));
 return <><div className="panel-title"><h2>Mẫu dựng</h2><Button small icon={Save} disabled={locked} onClick={onSave}>Lưu mẫu</Button></div><div className="template-grid">{templates.map(x=>{const template=x.template||x,missing=x.missing_assets||[],selectedMap=Object.fromEntries(missing.map(item=>[item.id,replacements[`${x.id}:${item.id}`]||'']));return <div key={x.id} className="template-choice"><button className={t.id===template.id?'active':''} disabled={locked} onClick={()=>x.built_in?edit(n=>{n.template=clone(template);n.mode='template'}):missing.length===0&&applyTemplate(x.id,{})}><div className={'template-art '+(template.id==='editorial'?'paper':template.id==='bold'?'bold':'')}><div/><i/><b>Aa</b></div><span>{x.name||template.name}</span>{x.saved&&<small>Đã lưu</small>}</button>{missing.map(item=><Field key={item.id} label={'Thiếu '+item.name}><select value={selectedMap[item.id]} disabled={locked} onChange={e=>setReplacements(old=>({...old,[`${x.id}:${item.id}`]:e.target.value}))}><option value="">Chọn ảnh thay thế</option>{p.assets.filter(a=>a.media==='image'&&!a.deleted).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field>)}{!x.built_in&&missing.length>0&&<Button small disabled={locked||missing.some(item=>!selectedMap[item.id])} onClick={()=>applyTemplate(x.id,selectedMap)}>Áp dụng template</Button>}</div>})}</div><div className="subsection"><h3>Từ video mẫu của bạn</h3><select value={ref} onChange={e=>setRef(e.target.value)}><option value="">Chọn video đã nhập ở vai trò Video mẫu</option>{p.assets.filter(a=>a.role==='reference'&&!a.deleted).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><label className="ai-toggle"><input type="checkbox" checked={useAI} onChange={e=>setUseAI(e.target.checked)}/>AI nhận diện bố cục, chữ và hình khối</label><Button icon={Sparkles} disabled={locked||!ref} onClick={()=>run('template',{asset_id:ref,use_ai:useAI})}>Phân tích mẫu</Button>{t.notes&&<p className="helper">{t.notes}</p>}</div>
 <Field label="Tên mẫu"><input value={t.name} onChange={e=>edit(n=>n.template.name=e.target.value)}/></Field><div className="row"><Field label="Màu nền"><input type="color" value={t.background} onChange={e=>edit(n=>n.template.background=e.target.value)}/></Field><Field label="Chuyển cảnh"><select value={t.transition} onChange={e=>edit(n=>{n.template.transition=e.target.value;n.clips.forEach(c=>c.transition=e.target.value)})}><option value="cut">Cắt thẳng</option><option value="fade">Mờ qua nền</option></select></Field></div><details className="advanced"><summary>Vị trí khung video</summary><div className="grid-two">{['x','y','w','h'].map(k=><NumberField key={k} label={{x:'Trái',y:'Trên',w:'Rộng',h:'Cao'}[k]+' (0–1)'} value={t.viewport[k]} max={1} step={.01} onChange={v=>edit(n=>n.template.viewport[k]=v)}/>)}</div></details>
 <div className="row spread"><h3>Các lớp trong mẫu</h3><div className="row"><Button small onClick={()=>addLayer('text')}>+ Chữ</Button><Button small onClick={()=>addLayer('rect')}>+ Khối</Button><Button small onClick={()=>addLayer('image')}>+ Logo</Button></div></div>{t.layers.map((l,i)=><details className="layer-card" key={l.id}><summary><span>{l.kind==='text'?'T':l.kind==='image'?'▧':'■'} · {l.text||l.kind}</span><button aria-label="Xóa lớp" onClick={e=>{e.preventDefault();edit(n=>n.template.layers.splice(i,1))}}><Trash2 size={13}/></button></summary><LayerEditor layer={l} p={p} onChange={(k,v)=>edit(n=>n.template.layers[i][k]=v)}/></details>)}
 <CaptionEditor style={t.caption} onChange={(k,v)=>edit(n=>n.template.caption[k]=v)}/><details className="advanced" onToggle={e=>{if(e.target.open)setJson(JSON.stringify(t,null,2))}}><summary>Template JSON / bố cục từng ô</summary><textarea className="code-input" value={json} onChange={e=>setJson(e.target.value)}/>{jsonError&&<p className="inline-error">{jsonError}</p>}<Button small onClick={async()=>{try{const parsed=await api('/templates/validate',JSON.parse(json));edit(n=>n.template=parsed);setJsonError('')}catch(e){setJsonError(e.message)}}}>Áp dụng JSON</Button></details></>
}

function LayerEditor({layer:l,p,onChange}){return <><Field label="Loại lớp"><select value={l.kind} onChange={e=>{onChange('kind',e.target.value);if(e.target.value!=='image')onChange('asset_id','')}}>{['text','rect','circle','image'].map(k=><option key={k}>{k}</option>)}</select></Field>{l.kind==='text'&&<Field label="Nội dung · {title}, {project}, {caption}"><input value={l.text} onChange={e=>onChange('text',e.target.value)}/></Field>}{l.kind==='image'&&<Field label="Logo / biểu tượng"><select value={l.asset_id} onChange={e=>onChange('asset_id',e.target.value)}><option value="">Chọn ảnh đã nhập</option>{p.assets.filter(a=>a.media==='image'&&!a.deleted).map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></Field>}<div className="grid-two">{['x','y','w','h'].map(k=><NumberField key={k} label={k} value={l[k]} max={1} step={.01} onChange={v=>onChange(k,v)}/>)}</div><div className="row"><Field label="Màu"><input type="color" value={l.color} onChange={e=>onChange('color',e.target.value)}/></Field><NumberField label="Cỡ chữ" value={l.size} min={12} max={200} step={1} onChange={v=>onChange('size',v)}/></div><Field label="Chuyển động"><select value={l.animation} onChange={e=>onChange('animation',e.target.value)}><option value="none">Tĩnh</option><option value="fade">Hiện dần</option><option value="slide">Trượt vào</option></select></Field><Field label="Độ đậm"><input type="range" min="0" max="1" step=".05" value={l.opacity} onChange={e=>onChange('opacity',Number(e.target.value))}/></Field></>}
function CaptionEditor({style:s,onChange}){return <div className="subsection"><h3>Phụ đề</h3><label className="ai-toggle"><input type="checkbox" checked={s.enabled} onChange={e=>onChange('enabled',e.target.checked)}/>Hiện phụ đề trên video</label><div className="row"><NumberField label="Cỡ chữ" value={s.font_size} min={18} max={120} step={1} onChange={v=>onChange('font_size',v)}/><Field label="Màu chữ"><input type="color" value={s.color} onChange={e=>onChange('color',e.target.value)}/></Field></div><NumberField label="Khoảng cách từ đáy (0–1)" value={s.bottom} min={.02} max={.8} step={.01} onChange={v=>onChange('bottom',v)}/><NumberField label="Số từ mỗi nhóm" value={s.words_per_line} min={2} max={12} step={1} onChange={v=>onChange('words_per_line',v)}/><label className="ai-toggle"><input type="checkbox" checked={s.karaoke} onChange={e=>onChange('karaoke',e.target.checked)}/>Tô sáng theo từ (karaoke)</label>{s.karaoke&&<Field label="Màu tô sáng"><input type="color" value={s.highlight} onChange={e=>onChange('highlight',e.target.value)}/></Field>}</div>}

function AudioPanel({p,edit,locked,run,upload,settings,onSettings}){return <><div className="panel-title"><h2>Giọng đọc & nhạc</h2><Volume2 size={20}/></div><div className="voice-provider"><Mic2 size={22}/><div><b>{settings?.tts_provider==='azure'?'Azure · Tiếng Việt':settings?.tts_provider==='windows'?'Giọng trên Windows':'OpenAI Speech'}</b><small>{settings?.tts_provider==='azure'?settings.azure_voice:settings?.tts_provider==='windows'?(settings.windows_voice||'Giọng mặc định'):settings?.tts_voice}</small></div><Button small onClick={onSettings}>Đổi</Button></div><Button primary icon={Sparkles} disabled={locked||!p.script.trim()} onClick={()=>run('voice')}>Tạo giọng từ kịch bản</Button><p className="helper">Giọng dịch vụ cần API key và Internet. Giọng Windows dùng các giọng đã cài trên máy; có thể chưa có tiếng Việt.</p><Field label="Giọng đọc đang dùng"><select value={p.voice_id} disabled={locked} onChange={e=>edit(n=>n.voice_id=e.target.value)}><option value="">Không có giọng đọc</option>{p.assets.filter(a=>a.role==='voice'&&!a.deleted).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><label className="upload-inline"><Upload size={15}/>Nhập file voice<input type="file" hidden accept="audio/*,video/*" disabled={locked} onChange={e=>upload(e.target.files,'voice')}/></label>{p.voice_id&&<><audio controls src={mediaUrl(p,p.voice_id)}/><Button small icon={FileText} disabled={locked} onClick={()=>run('transcribe',{asset_id:p.voice_id})}>Căn phụ đề từ voice</Button><p className="helper">Nhận dạng lại nội dung voice và mốc từng từ; thay kịch bản bằng lời đã nhận dạng.</p></>}<Field label={'Âm lượng voice · '+Math.round(p.voice_volume*100)+'%'}><input type="range" min="0" max="2" step=".05" value={p.voice_volume} onChange={e=>edit(n=>n.voice_volume=Number(e.target.value))}/></Field><div className="subsection"><h3>Nhạc nền</h3><select value={p.music_id} onChange={e=>edit(n=>n.music_id=e.target.value)}><option value="">Không có nhạc</option>{p.assets.filter(a=>a.role==='music'&&!a.deleted).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><label className="upload-inline"><Upload size={15}/>Nhập nhạc nền<input type="file" hidden accept="audio/*" disabled={locked} onChange={e=>upload(e.target.files,'music')}/></label>{p.music_id&&<audio controls src={mediaUrl(p,p.music_id)}/>}<Field label={'Âm lượng nhạc · '+Math.round(p.music_volume*100)+'%'}><input type="range" min="0" max="1" step=".01" value={p.music_volume} onChange={e=>edit(n=>n.music_volume=Number(e.target.value))}/></Field><label className="ai-toggle"><input type="checkbox" checked={p.ducking} onChange={e=>edit(n=>n.ducking=e.target.checked)}/>Tự giảm nhạc khi có lời đọc</label><p className="helper">Nhạc được lặp để đủ thời lượng và nhỏ dần ở cuối video.</p></div></>}

function ClipInspector({p,selected,edit,locked}){
 const c=p.clips[selected];if(!c)return <Empty icon={SlidersHorizontal} title="Chọn một cảnh">Các điều chỉnh sẽ hiện ở đây sau khi tạo timeline.</Empty>;
 const change=(k,v)=>edit(n=>n.clips[selected][k]=v);const a=aid(p,c.asset_id);
 return <fieldset disabled={locked} className="inspector-fields"><Field label="Tư liệu"><select value={c.asset_id} onChange={e=>edit(n=>{n.clips[selected].asset_id=e.target.value;n.clips[selected].source_start=0;n.clips[selected].scene_id=''})}>{p.assets.filter(a=>a.media!=='audio'&&a.role==='source'&&!a.deleted).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><Field label="Thay bằng cảnh"><select value={c.scene_id} onChange={e=>{const sc=a.scenes.find(s=>s.id===e.target.value);if(sc)edit(n=>{n.clips[selected].scene_id=sc.id;n.clips[selected].source_start=sc.start})}}><option value="">Tùy chỉnh</option>{a?.scenes.map((sc,i)=><option value={sc.id} key={sc.id}>Cảnh {i+1} · {fmt(sc.start)} · {sc.tags.slice(0,25)}</option>)}</select></Field><div className="grid-two"><NumberField label="Cắt từ (s)" value={c.source_start} max={a?.duration||0} step={.1} onChange={v=>{change('source_start',v)}}/><NumberField label="Dài (s)" value={c.duration} min={.2} max={180} step={.1} onChange={v=>change('duration',v)}/></div><Field label="Tiêu đề trong mẫu"><textarea rows="2" value={c.title} onChange={e=>change('title',e.target.value)}/></Field><Field label="Ghi đè phụ đề cảnh" hint="Để trống để dùng phụ đề theo voice."><textarea rows="2" value={c.caption} onChange={e=>change('caption',e.target.value)}/></Field><div className="grid-two"><Field label="Khung hình"><select value={c.fit} onChange={e=>change('fit',e.target.value)}><option value="cover">Lấp đầy / cắt</option><option value="contain">Giữ trọn hình</option></select></Field><NumberField label="Tốc độ" value={c.speed} min={.25} max={4} step={.05} onChange={v=>change('speed',v)}/></div><Field label="Vị trí cắt ngang"><input type="range" min="0" max="1" step=".01" value={c.crop_x} onChange={e=>change('crop_x',Number(e.target.value))}/></Field><Field label="Vị trí cắt dọc"><input type="range" min="0" max="1" step=".01" value={c.crop_y} onChange={e=>change('crop_y',Number(e.target.value))}/></Field><Field label="Chuyển cảnh"><select value={c.transition} onChange={e=>change('transition',e.target.value)}><option value="cut">Cắt thẳng</option><option value="fade">Mờ qua nền</option></select></Field><div className="row"><Button small icon={Copy} onClick={()=>edit(n=>{const cp=clone(n.clips[selected]);cp.id=crypto.randomUUID().slice(0,16);n.clips.splice(selected+1,0,cp)})}>Nhân đôi</Button><Button small icon={Trash2} onClick={()=>edit(n=>n.clips.splice(selected,1))}>Xóa</Button></div></fieldset>
}

function AssistantPanel({p,locked,run,proposal,onApply,onSettings}){const [prompt,setPrompt]=useState('');return <><div className="panel-title"><h2>Trợ lý dựng video</h2><Sparkles size={20}/></div><div className="assistant-intro"><div className="ai-orb"><Sparkles size={26}/></div><h3>Bạn muốn thay đổi điều gì?</h3><p>AI đề xuất thay cảnh, chỉnh chữ, kịch bản hoặc âm lượng. Bạn xem đề xuất trước khi áp dụng.</p></div><div className="suggestion-list">{['Viết phần mở đầu cuốn hút hơn, giữ video khoảng 36 giây.','Giảm nhạc nền còn 10%.','Rút ngắn tiêu đề các cảnh còn tối đa 6 từ.'].map(text=><button key={text} onClick={()=>setPrompt(text)}>{text}<ArrowRight size={14}/></button>)}</div><textarea rows="4" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ví dụ: đổi tiêu đề cảnh 3 thành…"/><Button primary icon={Send} disabled={locked||!prompt.trim()} onClick={()=>run('assistant',{prompt})}>Gửi yêu cầu</Button><p className="helper">Kịch bản và danh sách cảnh sẽ được gửi đến API bạn cấu hình. <button className="text-link" onClick={onSettings}>Cài đặt kết nối</button></p>{proposal&&<div className="proposal"><h3>Đề xuất chỉnh sửa</h3><p>{proposal.message}</p>{proposal.script&&<blockquote>{proposal.script}</blockquote>}{proposal.music_volume!=null&&<p>Nhạc nền: {Math.round(proposal.music_volume*100)}%</p>}{proposal.clip_changes?.map((c,i)=><p key={i}>Cảnh {p.clips.findIndex(x=>x.id===c.id)+1}: {Object.entries(c).filter(([k])=>k!=='id').map(([k,v])=>`${k}: ${v}`).join(' · ')}</p>)}<Button icon={Check} primary disabled={locked} onClick={onApply}>Áp dụng đề xuất</Button></div>}</>}

function Preview({p,selected,preview,play,setPlay,cursor,setCursor,duration,onSelect}){
 const video=useRef(),voice=useRef(),music=useRef();const [size,setSize]=useState(280);const canvas=useRef();const posRef=useRef(cursor);posRef.current=cursor;
 let offset=0,index=0;for(let i=0;i<p.clips.length;i++){if(cursor>=offset&&cursor<offset+p.clips[i].duration){index=i;break}offset+=p.clips[i].duration;index=i}
 const c=p.clips[index]||p.clips[selected],a=c&&aid(p,c.asset_id),local=cursor-p.clips.slice(0,index).reduce((n,c)=>n+c.duration,0);const t=p.template;
 useEffect(()=>{const observer=new ResizeObserver(entries=>setSize(entries[0].contentRect.width));if(canvas.current)observer.observe(canvas.current);return()=>observer.disconnect()},[p.id,p.aspect,preview]);
 useEffect(()=>{if(!play)return;let frame,last;const tick=time=>{if(last){const next=posRef.current+(time-last)/1000;if(next>=duration){setCursor(duration);setPlay(false);return}setCursor(next)}last=time;frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[play,duration]);
 useEffect(()=>{if(play)onSelect(index)},[index,play]);
 useEffect(()=>{const v=video.current;if(!v||!c)return;v.playbackRate=c.speed;const wanted=c.source_start+Math.max(0,local)*c.speed;const sc=a?.scenes.find(s=>s.id===c.scene_id);const end=sc?.end||a?.duration||999;const time=Math.min(wanted,end-.04);if(Math.abs(v.currentTime-time)>.3)v.currentTime=Math.max(0,time);if(play&&wanted<end)v.play().catch(()=>{});else v.pause()},[cursor,play,c?.id,c?.source_start,c?.speed]);
 useEffect(()=>{for(const [ref,id,volume] of [[voice,p.voice_id,p.voice_volume],[music,p.music_id,p.music_volume]]){const audio=ref.current;if(!audio||!id)continue;audio.volume=Math.min(1,volume);const time=ref===music&&Number.isFinite(audio.duration)?cursor%audio.duration:cursor;if(Math.abs(audio.currentTime-time)>.4)audio.currentTime=Math.max(0,time);if(play)audio.play().catch(()=>{});else audio.pause()}},[cursor,play,p.voice_id,p.music_id,p.voice_volume,p.music_volume]);
 const layers=c?[...t.layers,...(p.mode==='template'&&t.slot_layers?.length?t.slot_layers[index%t.slot_layers.length]:[]),...(c.layers||[])]:[];
 const cue=p.cues.find(x=>cursor>=x.start&&cursor<x.end);let text=c?.caption||cue?.text||'';if(!c?.caption&&cue){const words=cue.text.split(/\s+/);const fraction=(cursor-cue.start)/(cue.end-cue.start);const group=Math.floor(fraction*words.length/t.caption.words_per_line);text=words.slice(group*t.caption.words_per_line,(group+1)*t.caption.words_per_line).join(' ')}
 return <div className="preview-stage">{preview?<video className="rendered-video" controls autoPlay src={exportUrl(p,preview)}/>:<div ref={canvas} className={'video-canvas aspect-'+p.aspect.replace(':','-')} style={{background:t.background}}>{a?<><div className="video-viewport" style={{left:t.viewport.x*100+'%',top:t.viewport.y*100+'%',width:t.viewport.w*100+'%',height:t.viewport.h*100+'%'}}>{a.media==='image'?<img src={mediaUrl(p,a.id)} style={{objectFit:c.fit,objectPosition:`${c.crop_x*100}% ${c.crop_y*100}%`}}/>:<video ref={video} src={mediaUrl(p,a.id)} muted playsInline onLoadedMetadata={()=>{if(video.current)video.current.currentTime=c.source_start}} style={{objectFit:c.fit,objectPosition:`${c.crop_x*100}% ${c.crop_y*100}%`}}/>}</div>{layers.map((l,i)=><div className="canvas-layer" key={l.id+'-'+i} style={{left:l.x*100+'%',top:l.y*100+'%',width:l.w*100+'%',height:l.h*100+'%',fontSize:Math.max(8,l.size*size/1080),color:l.color,opacity:l.opacity,background:l.kind==='rect'||l.kind==='circle'?l.color:'transparent',borderRadius:l.kind==='circle'?'50%':0}}>{l.kind==='text'?l.text.replaceAll('{title}',c.title).replaceAll('{project}',p.name).replaceAll('{caption}',c.caption):l.kind==='image'&&l.asset_id?<img src={mediaUrl(p,l.asset_id)}/>:null}</div>)}{t.caption.enabled&&text&&<div className="canvas-caption" style={{bottom:t.caption.bottom*100+'%',fontSize:Math.max(9,t.caption.font_size*size/1080),color:t.caption.color,textShadow:[1,3,5].reduce((sum,i)=>sum+parseInt(t.caption.color.slice(i,i+2),16),0)<360?'0 1px 1px #ffffff':'0 1px 2px #000,1px 0 2px #000,-1px 0 2px #000'}}>{text}</div>}</>:<div className="canvas-placeholder"><Clapperboard size={36}/><span>Câu chuyện bắt đầu<br/>từ cảnh đầu tiên.</span><small>{p.aspect} · {p.target_duration}s</small></div>}</div>}{p.voice_id&&<audio ref={voice} src={mediaUrl(p,p.voice_id)}/>} {p.music_id&&<audio ref={music} loop src={mediaUrl(p,p.music_id)}/>}</div>
}

function SettingsModal({settings,onClose,onSave,onTest,onUseEnvironment}) {
 const [s,setS]=useState(()=>clone(settings));
 const [selectedId,setSelectedId]=useState(settings.active_ai_profile_id||settings.ai_profiles?.[0]?.id||'');
 const [newProvider,setNewProvider]=useState('gemini');
 const [showKey,setShowKey]=useState(false);
 const [note,setNote]=useState('');
 const [testing,setTesting]=useState(false);
 const [voices,setVoices]=useState([]);
 const keyInput=useRef(null);
 const switchToEnvironment=async secret=>{setNote('Đang chuyển cấu hình…');const next=await onUseEnvironment(secret,s);if(next){setS(next);setSelectedId(next.active_ai_profile_id||next.ai_profiles?.[0]?.id||'');setNote('Đã chọn dùng khóa từ biến môi trường.');}};
 useEffect(()=>{api('/voices/windows').then(setVoices).catch(()=>{})},[]);
 const field=(key,value)=>setS(old=>({...old,[key]:value}));
 const profiles=s.ai_profiles||[];
 const profile=profiles.find(x=>x.id===selectedId)||profiles[0];
 const initialProfile=settings.ai_profiles?.find(x=>x.id===profile?.id);
 const savedKey=initialProfile?.api_key==='••••••••';
 const changedKey=profile&&profile.api_key!==initialProfile?.api_key;
 const editProfile=(id,patch)=>setS(old=>({...old,ai_profiles:old.ai_profiles.map(x=>x.id===id?{...x,...patch}:x)}));
 const addProfile=()=>{
  const names={openai:'OpenAI',gemini:'Gemini',compatible:'API tương thích'};
  const defaults={openai:'gpt-4o-mini',gemini:'gemini-2.5-flash',compatible:'model-name'};
  const item={id:crypto.randomUUID(),name:names[newProvider]+' '+(profiles.length+1),provider:newProvider,api_key:'',model:defaults[newProvider],base_url:'',enabled:true};
  setS(old=>({...old,ai_profiles:[...old.ai_profiles,item],active_ai_profile_id:old.active_ai_profile_id||item.id}));
  setSelectedId(item.id);setShowKey(false);setNote('');
 };
 const removeProfile=id=>{
  const remaining=profiles.filter(x=>x.id!==id);
  setS(old=>({...old,ai_profiles:remaining,active_ai_profile_id:old.active_ai_profile_id===id?(remaining[0]?.id||''):old.active_ai_profile_id}));
  setSelectedId(remaining[0]?.id||'');setNote('');
 };
 const moveProfile=(id,delta)=>{
  const index=profiles.findIndex(x=>x.id===id),target=index+delta;
  if(target<0||target>=profiles.length)return;
  const reordered=[...profiles];[reordered[index],reordered[target]]=[reordered[target],reordered[index]];
  field('ai_profiles',reordered);
 };
 const pasteKey=async()=>{
  if(!profile)return;
  try {
   const value=(await navigator.clipboard.readText()).trim();
   if(!value){setNote('Clipboard đang trống. Bạn có thể nhấn Ctrl+V vào ô khóa.');return}
   editProfile(profile.id,{api_key:value});
   setNote('Đã dán khóa. Nhấn “Lưu cài đặt” để hoàn tất.');
  } catch {
   keyInput.current?.focus();keyInput.current?.select();
   setNote('Trình duyệt không cho đọc clipboard. Nhấn Ctrl+V vào ô đã chọn.');
  }
 };
 const testConnection=async()=>{
  if(!profile)return;
  setTesting(true);setNote('');
  try {
   const result=await onTest(s,profile.id);
   if(result){
    setS(result.settings);
    setNote((result.message||'Kết nối AI thành công')+' · '+result.route.name+' / '+result.route.model);
   }
  } finally {setTesting(false)}
 };
 return <div className="modal-backdrop" onClick={onClose}>
  <section className="settings-modal multi-api-modal" role="dialog" aria-modal="true" aria-label="Cài đặt nhiều API" onClick={e=>e.stopPropagation()}>
   <div className="modal-header"><div><span className="eyebrow">CLIPFORGE LOCAL</span><h2>API, model và giọng đọc</h2></div><button className="icon-button" onClick={onClose} aria-label="Đóng cài đặt"><X/></button></div>
   <div className="modal-body">
    <div className="api-section-header"><div><h3>Các cấu hình AI</h3><p>Chọn API chính. Khi lỗi, chương trình thử các cấu hình còn lại theo thứ tự trong danh sách.</p></div></div>
    <div className="api-add-row"><select aria-label="Loại API mới" value={newProvider} onChange={e=>setNewProvider(e.target.value)}><option value="gemini">Gemini</option><option value="openai">OpenAI</option><option value="compatible">API tương thích OpenAI</option></select><Button icon={Plus} onClick={addProfile}>Thêm API</Button></div>
    {!profiles.length&&<div className="api-empty">Chưa có API. Chọn loại ở trên và bấm “Thêm API”.</div>}
    <div className="api-profile-list">{profiles.map((item,index)=><div key={item.id} className={'api-profile-row '+(profile?.id===item.id?'selected':'')}>
     <button className="api-profile-select" onClick={()=>{setSelectedId(item.id);setShowKey(false);setNote('')}}><strong>{item.name}</strong><small>{item.provider==='gemini'?'Gemini':item.provider==='openai'?'OpenAI':'API tương thích'} · {item.model} · {item.api_key?'Có khóa':'Chưa có khóa'}{!item.enabled?' · Đang tắt':''}</small></button>
     <button className={'profile-priority '+(s.active_ai_profile_id===item.id?'active':'')} onClick={()=>field('active_ai_profile_id',item.id)} aria-label={'Đặt '+item.name+' làm API chính'} title="Đặt làm API chính">{s.active_ai_profile_id===item.id?'Chính':'Dùng chính'}</button>
     <button className="profile-move" disabled={index===0} onClick={()=>moveProfile(item.id,-1)} aria-label={'Tăng ưu tiên '+item.name}>↑</button>
     <button className="profile-move" disabled={index===profiles.length-1} onClick={()=>moveProfile(item.id,1)} aria-label={'Giảm ưu tiên '+item.name}>↓</button>
    </div>)}</div>
    {profile&&<div className="api-key-card profile-editor" key={profile.id}>
     <div className="api-key-heading"><div className="api-key-icon"><KeyRound size={20}/></div><div><h3>Chỉnh {profile.name}</h3><p>{s.active_ai_profile_id===profile.id?'API chính':'API dự phòng'} · {profile.enabled?'Đang bật':'Đang tắt'}</p></div><button className="profile-remove" onClick={()=>removeProfile(profile.id)} aria-label={'Xóa '+profile.name}>Xóa</button></div>
     <div className="grid-two"><Field label="Tên cấu hình"><input value={profile.name} maxLength={80} onChange={e=>editProfile(profile.id,{name:e.target.value})}/></Field><Field label="Loại API"><select value={profile.provider} onChange={e=>editProfile(profile.id,{provider:e.target.value})}><option value="gemini">Gemini</option><option value="openai">OpenAI</option><option value="compatible">API tương thích OpenAI</option></select></Field></div>
     <div className="grid-two"><Field label="Model"><input value={profile.model} onChange={e=>editProfile(profile.id,{model:e.target.value})} placeholder="Tên model của nhà cung cấp"/></Field>{profile.provider==='compatible'?<Field label="API base URL"><input value={profile.base_url} onChange={e=>editProfile(profile.id,{base_url:e.target.value})} placeholder="https://.../v1"/></Field>:<div className="profile-endpoint"><span>Endpoint</span><small>{profile.provider==='gemini'?'Gemini API (Google)':'OpenAI API'}</small></div>}</div>
     <label className="field" htmlFor="profile-api-key"><span>API key {savedKey&&!changedKey?'· đã lưu':''}</span></label>
     <div className="secret-input"><input id="profile-api-key" ref={keyInput} type={showKey?'text':'password'} autoComplete="off" spellCheck="false" value={profile.api_key} placeholder="Dán API key vào đây" onFocus={e=>{if(savedKey&&!changedKey)e.target.select()}} onChange={e=>{editProfile(profile.id,{api_key:e.target.value});setNote('')}}/><button type="button" onClick={()=>setShowKey(!showKey)} aria-label={showKey?'Ẩn API key':'Hiện API key'}>{showKey?<EyeOff size={16}/>:<Eye size={16}/>}</button></div>
     <div className="key-actions"><Button small icon={ClipboardPaste} onClick={pasteKey}>Dán từ clipboard</Button><Button small icon={Check} disabled={!profile.api_key||!profile.enabled||testing} onClick={testConnection}>{testing?'Đang kiểm tra…':'Lưu và kiểm tra API này'}</Button></div>
     <label className="ai-toggle"><input type="checkbox" checked={profile.enabled} onChange={e=>editProfile(profile.id,{enabled:e.target.checked})}/>Bật cấu hình này</label>
     {note&&<p className="key-note" role="status">{note}</p>}
    </div>}
    <label className="fallback-toggle"><input type="checkbox" checked={s.ai_auto_fallback} onChange={e=>field('ai_auto_fallback',e.target.checked)}/><span><b>Tự chuyển API khi lỗi</b><small>Thử cấu hình chính trước, rồi lần lượt các cấu hình đang bật còn lại. Áp dụng cho phân tích cảnh, dựng bằng AI và trợ lý.</small></span></label>
    {settings.environment_available?.ai&&<div className="subsection"><Button small icon={KeyRound} onClick={()=>switchToEnvironment('ai')}>Dùng OPENAI_API_KEY từ môi trường</Button><p className="helper">Thao tác này đặt cấu hình API môi trường làm cấu hình chính. Khóa đã lưu khác vẫn được giữ.</p></div>}
    <p className="helper">Khóa lưu trong <code>data/settings.json</code> trên máy; mở lại chỉ thấy ký hiệu che khóa. Chọn model có hỗ trợ ảnh và trả JSON cho tính năng phân tích mẫu/cảnh.</p>
    <h3>Tạo giọng đọc</h3>
    <p className="helper">OpenAI Speech dùng khóa OpenAI hoặc API tương thích đang bật. Gemini trong danh sách trên dùng cho tác vụ biên tập, không dùng cho Speech.</p>
    <Field label="Nhà cung cấp"><select value={s.tts_provider} onChange={e=>field('tts_provider',e.target.value)}><option value="openai">OpenAI / API tương thích</option><option value="azure">Azure Speech · Tiếng Việt</option><option value="windows">Giọng cài trên Windows</option></select></Field>
    {s.tts_provider==='openai'?<div className="grid-two"><Field label="Model tạo giọng"><input value={s.tts_model} onChange={e=>field('tts_model',e.target.value)}/></Field><Field label="Tên giọng"><input value={s.tts_voice} onChange={e=>field('tts_voice',e.target.value)}/></Field></div>:s.tts_provider==='azure'?<><Field label="Azure Speech key"><input type="password" autoComplete="off" spellCheck="false" value={s.azure_key} onChange={e=>field('azure_key',e.target.value)}/></Field>{settings.environment_available?.azure&&<Button small icon={KeyRound} onClick={()=>switchToEnvironment('azure')}>Dùng AZURE_SPEECH_KEY từ môi trường</Button>}<div className="grid-two"><Field label="Region"><input value={s.azure_region} onChange={e=>field('azure_region',e.target.value)}/></Field><Field label="Giọng"><select value={s.azure_voice} onChange={e=>field('azure_voice',e.target.value)}><option>vi-VN-HoaiMyNeural</option><option>vi-VN-NamMinhNeural</option></select></Field></div></>:<Field label="Giọng đã cài"><select value={s.windows_voice} onChange={e=>field('windows_voice',e.target.value)}><option value="">Giọng mặc định</option>{voices.map(v=><option key={v.name} value={v.name}>{v.name} · {v.culture}</option>)}</select></Field>}
    <NumberField label="Tốc độ đọc" value={s.tts_speed} min={.5} max={2} step={.05} onChange={v=>field('tts_speed',v)}/>
    <h3>Căn phụ đề từ audio</h3>
    <Field label="Bộ nhận dạng"><select value={s.transcription_provider} onChange={e=>field('transcription_provider',e.target.value)}><option value="openai">API · word timestamps</option><option value="local">Faster Whisper · trên máy</option></select></Field>
    <div className="grid-two"><Field label="Model"><input value={s.transcription_provider==='local'?s.local_whisper_model:s.transcription_model} onChange={e=>field(s.transcription_provider==='local'?'local_whisper_model':'transcription_model',e.target.value)}/></Field><Field label="Mã ngôn ngữ"><input value={s.language} onChange={e=>field('language',e.target.value)}/></Field></div>
   </div>
   <div className="modal-footer"><Button onClick={onClose}>Đóng</Button><Button primary icon={Save} onClick={()=>onSave(s)}>Lưu cài đặt</Button></div>
  </section>
 </div>
}

createRoot(document.getElementById('root')).render(<App/>);
